from datetime import datetime, timezone
from typing import Optional


# A service's tone/accent-colour/icon are all derived from its type (category)
# name — this mirrors the frontend's TYPE_META map so the same visuals appear.
TYPE_TONES = {
    "Fashion": "brand",
    "Beauty": "violet",
    "Photography": "amber",
    "Digital": "sky",
    "Wellness": "emerald",
}
# Category colours are generated by the theme engine, not chosen here. A fixed
# list collided with the theme — under an amber theme the "brand" tone became
# amber and two categories rendered almost identically. The engine spreads
# CATEGORY_SLOTS hues evenly from the user's own primary, so slices are always
# distinguishable and always belong to the chosen palette.
CATEGORY_SLOTS = 8


def _hash_slot(name: str) -> int:
    """Mirrors theme-engine/categorical.ts — same hash on both sides."""
    h = 0
    for ch in (name or ""):
        h = (h * 31 + ord(ch)) & 0xFFFFFFFF
    return h % CATEGORY_SLOTS


def assign_slots(names: list[str]) -> dict[str, int]:
    """
    A distinct colour slot per category.

    Hash alone collides — with 8 slots and 5 categories, Fashion and Digital
    both landed on 1, so two rows looked identical. Start from the hash (so a
    name keeps its colour as the set grows) and probe forward to the next free
    slot, which guarantees distinctness for up to CATEGORY_SLOTS categories.
    """
    taken: set[int] = set()
    out: dict[str, int] = {}
    for name in sorted(set(n for n in names if n)):
        start = _hash_slot(name)
        for offset in range(CATEGORY_SLOTS):
            slot = (start + offset) % CATEGORY_SLOTS
            if slot not in taken:
                taken.add(slot)
                out[name] = slot + 1
                break
        else:
            # More categories than slots — wrap round and accept a repeat.
            out[name] = (start % CATEGORY_SLOTS) + 1
    return out


def category_slot(name: str) -> int:
    """Single-name fallback for callers without the full set."""
    return _hash_slot(name) + 1
TYPE_ICONS = {
    "Fashion": "Scissors",
    "Beauty": "Sparkles",
    "Photography": "Camera",
    "Digital": "Monitor",
    "Wellness": "HeartPulse",
}


def tone_for_type(type_name: str) -> str:
    return TYPE_TONES.get(type_name, "brand")


# Icons were derived from the TYPE alone, so every service in a category shared
# one icon — "Beauty & Makeup" and "Mehndi Design" were both Sparkles, which
# makes a list impossible to scan. Match on the service's own name first, and
# fall back to its type only when nothing specific fits.
NAME_ICONS = [
    (("tailor", "stitch", "sewing", "garment", "blouse"), "Scissors"),
    (("mehndi", "henna", "mehandi"), "Flower2"),
    (("makeup", "beauty", "salon", "hair", "skin"), "Sparkles"),
    (("photo", "camera", "shoot"), "Camera"),
    (("digital", "marketing", "computer", "online", "web"), "Monitor"),
    (("health", "wellness", "yoga", "fitness", "nutrition"), "HeartPulse"),
    (("craft", "handicraft", "embroider", "weav"), "Leaf"),
    (("business", "entrepreneur", "finance", "account"), "Briefcase"),
]


def icon_for_service(name: str, type_name: str = "") -> str:
    """A specific icon for this service, or its type's icon as a fallback."""
    lowered = (name or "").lower()
    for keywords, icon in NAME_ICONS:
        if any(k in lowered for k in keywords):
            return icon
    return TYPE_ICONS.get(type_name, "Briefcase")


def icon_for_type(type_name: str) -> str:
    return TYPE_ICONS.get(type_name, "Briefcase")


def color_for_type(name: str) -> str:
    return f"var(--cat-{category_slot(name)})"


def icon_for_category(name: str) -> str:
    return TYPE_ICONS.get(name, "LayoutGrid")


class ServiceModel:
    """The 'services' collection — individual services shown on Services & Types."""

    collection_name = "services"

    TYPES = ["Fashion", "Beauty", "Photography", "Digital", "Wellness"]
    STATUSES = ["Active", "Inactive"]

    @staticmethod
    def create_document(
        name: str,
        type: str = "Fashion",
        duration: str = "60 min",
        price: str = "₹0",
        status: str = "Active",
        bookings: int = 0,
        rating: str = "0.0",
        description: str = "",
        tone: Optional[str] = None,
        created_at: Optional[datetime] = None,
    ) -> dict:
        now = datetime.now(timezone.utc)
        return {
            "name": name.strip(),
            "type": type,
            "tone": tone or tone_for_type(type),
            "duration": duration,
            "price": price,   # a display string the UI shows verbatim, e.g. "₹499"
            "status": status,
            "bookings": bookings,
            "rating": rating,   # kept as a label string, e.g. "4.9"
            "description": description.strip(),
            "created_at": created_at or now,
            "updated_at": now,
        }

    @staticmethod
    def to_response(doc: dict) -> dict:
        stype = doc.get("type", "")
        return {
            "id": str(doc["_id"]),
            "name": doc.get("name", ""),
            "type": stype,
            "tone": doc.get("tone") or tone_for_type(stype),
            "slot": category_slot(stype),
            "icon": icon_for_service(doc.get("name", ""), stype),
            "duration": doc.get("duration", ""),
            "price": doc.get("price", ""),
            "status": doc.get("status", "Active"),
            "bookings": doc.get("bookings", 0),
            "rating": doc.get("rating", "0.0"),
            "description": doc.get("description", ""),
        }


class ServiceTypeModel:
    """The 'service_types' collection — service categories (the Types table)."""

    collection_name = "service_types"

    STATUSES = ["Active", "Inactive"]

    @staticmethod
    def create_document(
        name: str,
        desc: str = "",
        services: int = 0,
        status: str = "Active",
        pop: int = 0,
        color: Optional[str] = None,
        created_at: Optional[datetime] = None,
    ) -> dict:
        now = datetime.now(timezone.utc)
        clean_name = name.strip()
        return {
            "name": clean_name,
            "desc": desc.strip(),
            "services": services,
            "status": status,
            "pop": pop,   # popularity 0-100
            "color": color or color_for_type(clean_name),
            "created_at": created_at or now,
            "updated_at": now,
        }

    @staticmethod
    def to_response(doc: dict) -> dict:
        name = doc.get("name", "")
        return {
            "id": str(doc["_id"]),
            "name": name,
            "desc": doc.get("desc", ""),
            "services": doc.get("services", 0),
            "status": doc.get("status", "Active"),
            "pop": doc.get("pop", 0),
            # Always derived — a stored hex would outlive the theme.
            "color": color_for_type(name),
            "slot": category_slot(name),
            "icon": icon_for_category(name),
        }
