import puppeteer from "puppeteer-core";
import { CHROME } from "./_shared.mjs";
const b = await puppeteer.launch({ executablePath: CHROME, headless: "new", args: ["--no-sandbox"] });
const p = await b.newPage();
const msgs = [];
p.on("console", m => { if (m.type() === "error" || m.type() === "warning") msgs.push(`${m.type()}: ${m.text().slice(0,6000)}`); });
p.on("pageerror", e => msgs.push("PAGEERROR: " + String(e).slice(0,160)));
p.on("requestfailed", r => msgs.push("FAILED: " + r.url().slice(0,100)));
await p.setViewport({ width: 1440, height: 900 });
await p.goto("http://localhost:3200/", { waitUntil: "networkidle2", timeout: 180000 });
await new Promise(r => setTimeout(r, 5000));
console.log(msgs.length ? msgs.slice(0,10).join("\n") : "  no console errors or warnings");
await b.close();
