"use client";
import Link from "next/link";
import Image from "next/image";
import { useMemo,useState } from "react";
import {HomeShell} from "@/components/ux/home/HomeShell";
import {I} from "@/components/ux/kit";
import s from "./schedule.module.css";

type Cat="learning"|"work"|"health"|"community"|"personal"|"money"|"mentoring";
type Module="calendar"|"agenda"|"bookings"|"reminders"|"focus";
const cats:[Cat,string,string][]=[["learning","Learning","GraduationCap"],["work","Work","Briefcase"],["health","Health","HeartPulse"],["community","Community","Users"],["personal","Personal","Sparkles"],["money","Money","Wallet"],["mentoring","Mentoring","UserRound"]];
const days=[["Sun",13],["Mon",14],["Tue",15],["Wed",16],["Thu",17],["Fri",18],["Sat",19]] as const;
const data:[number,number,number,string,string,Cat,string][]=[
 [0,1,1,"Morning Walk","7:00 - 8:00 AM","health","Leaf"],[0,4,1.5,"UI/UX Course","10:00 - 11:30 AM","learning","Laptop"],[0,7,1,"Lunch Break","1:00 - 2:00 PM","personal","Coffee"],[0,10,1,"Yoga Session","4:00 - 5:00 PM","health","Activity"],[0,14,1,"Reading Time","8:00 - 9:00 PM","learning","BookOpen"],
 [1,3,1.5,"Work on Project","9:00 - 10:30 AM","work","Briefcase"],[1,8,1.5,"Circle Meetup","2:00 - 3:30 PM","community","Users"],[2,2,1,"Meditation","8:00 - 9:00 AM","health","Heart"],[2,5,1.5,"Financial Planning","11:00 - 12:30 PM","money","TrendingUp"],[2,11,1,"Skill Practice","5:00 - 6:00 PM","learning","Sparkles"],
 [3,3,1,"Tailoring Class","9:00 - 10:00 AM","mentoring","GraduationCap"],[3,9,1,"Mentoring Call","3:00 - 4:00 PM","work","UserRound"],[3,13,1.5,"Family Time","7:00 - 8:30 PM","community","Users"],[4,4.5,1.5,"Webinar","10:30 AM - 12:00 PM","health","Mic"],[4,10,1,"Travel Planning","4:00 - 5:00 PM","personal","Plane"],
 [5,1,1,"Fitness","7:00 - 8:00 AM","community","Activity"],[5,7,1,"Lunch with Friend","1:00 - 2:00 PM","community","Briefcase"],[5,12,1.5,"Creative Time","6:00 - 7:30 PM","mentoring","Palette"],[6,3,1.5,"Online Course","9:00 - 10:30 AM","work","Laptop"],[6,9,1,"Community Activity","3:00 - 4:00 PM","health","Sprout"]
];
const hours=["6 AM","7 AM","8 AM","9 AM","10 AM","11 AM","12 PM","1 PM","2 PM","3 PM","4 PM","5 PM","6 PM","7 PM","8 PM","9 PM"];
const mini=[30,31,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3];
const moduleTabs:[Module,string,string][]=[["calendar","Calendar","CalendarDays"],["agenda","Agenda","List"],["bookings","My bookings","BookOpenCheck"],["reminders","Reminders","Bell"],["focus","Focus time","Clock3"]];
const moduleContent={
 bookings:{title:"My bookings",subtitle:"Your confirmed sessions and upcoming reservations.",items:[["Tailoring & Stitching","29 Sep · 9:00 AM · Online","GraduationCap","learning","View booking"],["Career counselling with Ananya","3 Oct · 11:00 AM · Video call","UserRound","mentoring","Join session"],["Women in Tech webinar","4 Oct · 4:00 PM · Online","Laptop","work","View details"]]},
 reminders:{title:"Reminders",subtitle:"Small prompts that keep important plans from slipping away.",items:[["Morning workout","Tomorrow · 7:00 AM","Activity","health","Edit reminder"],["Complete course module 2","20 Sep · 6:00 PM","BookOpen","learning","Mark complete"],["Review monthly savings","25 Sep · 9:00 AM","PiggyBank","money","Review goal"]]},
 focus:{title:"Focus time",subtitle:"Protect a quiet block for the work that matters most.",items:[["Quick focus","25 minutes · Short task","Timer","personal","Start 25 min"],["Deep work","50 minutes · One meaningful task","Brain","work","Start 50 min"],["Learning block","40 minutes · Course or practice","GraduationCap","learning","Start learning"]]},
} as const;

export default function Schedule(){
 const [view,setView]=useState("week"),[module,setModule]=useState<Module>("calendar"),[selected,setSelected]=useState(6),[off,setOff]=useState<Cat[]>([]),[add,setAdd]=useState(false);
 const shown=useMemo(()=>data.filter(e=>!off.includes(e[5])),[off]); const today=shown.filter(e=>e[0]===selected);
 const toggle=(c:Cat)=>setOff(x=>x.includes(c)?x.filter(v=>v!==c):[...x,c]);
 const rail=<div className={s.rail}><section className={s.mini}><header><h2>September 2026</h2><div><button aria-label="Previous month"><I name="ChevronLeft"/></button><button aria-label="Next month"><I name="ChevronRight"/></button></div></header><div className={s.miniWeek}>{["S","M","T","W","T","F","S"].map((x,i)=><b key={i}>{x}</b>)}</div><div className={s.miniDays}>{mini.map((x,i)=><button className={x===19?s.today:""} key={i}>{x}</button>)}</div><div className={s.todayList}><header><h3>Today · Sat, 19 Sep</h3><span>{today.length} activities</span></header>{today.map((e,i)=><Link href="/app/schedule" className={s.todayItem} data-cat={e[5]} key={i}><span>{e[4].split(" - ")[0]}</span><i><I name={e[6]}/></i><b>{e[3]}<small>{e[5]} · Online</small></b></Link>)}<button onClick={()=>setView("list")} className={s.full}>View full day <I name="ArrowRight"/></button></div></section><blockquote className={s.quote}>“Well planned days<br/>lead to a happier you.”<cite>— WomSakhi</cite></blockquote><section className={s.quick}><h3>Quick Add</h3><div>{[["CalendarPlus","Event"],["Bell","Reminder"],["ListChecks","Task"],["Target","Goal"]].map(x=><button onClick={()=>setAdd(true)} key={x[1]}><i><I name={x[0]}/></i>{x[1]}</button>)}</div><button className={s.natural}><I name="Sparkles"/> Add with natural language</button></section></div>;
 return <HomeShell active="/app/schedule" rail={rail}><main className={s.page}>
  <section className={s.hero}><Image src="/ux/schedule/calendar-hero-v1.png" alt="Woman enjoying a calm moment while planning her day" fill priority sizes="(max-width: 760px) 100vw, 75vw"/><div className={s.shade}/><div className={s.heroCopy}><p>← Home&nbsp; / &nbsp;<b>Your Calendar</b></p><h1>Your <em>Calendar</em></h1><span>Plan your time, stay consistent, and make space for what matters.</span></div><p className={s.note}>A balanced<br/>you builds<br/>a brighter<br/>tomorrow ♥<small>— WomSakhi</small></p></section>
  <nav className={s.nav}>{moduleTabs.map(([id,label,icon])=><button className={module===id?s.active:""} aria-pressed={module===id} onClick={()=>{setModule(id);if(id==="agenda")setView("list");if(id==="calendar"&&view==="list")setView("week")}} key={id}><I name={icon}/>{label}</button>)}<div className={s.add}><button onClick={()=>setAdd(!add)}><I name="Plus"/> Add activity</button>{add&&<div>{[["Book a mentor","/app/mentors"],["Join an event","/app/events"],["Start a course","/app/programs"]].map(x=><Link key={x[1]} href={x[1]}>{x[0]}<I name="ArrowRight"/></Link>)}</div>}</div></nav>
  {(module==="calendar"||module==="agenda")&&<><section className={s.controls}><div><button>Today</button><button aria-label="Previous week"><I name="ChevronLeft"/></button><button aria-label="Next week"><I name="ChevronRight"/></button><h2>September 2026 <I name="ChevronDown"/></h2></div><div className={s.switch}>{["day","week","month","list"].map(x=><button aria-pressed={view===x} onClick={()=>{setView(x);setModule(x==="list"?"agenda":"calendar")}} key={x}>{x}</button>)}</div><button className={s.filter}><I name="SlidersHorizontal"/> Filters</button></section><div className={s.filters}><button className={!off.length?s.on:""} onClick={()=>setOff([])}>All</button>{cats.map(c=><button data-cat={c[0]} aria-pressed={!off.includes(c[0])} onClick={()=>toggle(c[0])} key={c[0]}><I name={c[2]}/>{c[1]}</button>)}</div>{view==="week"||view==="day"?<section className={s.week}><div className={s.corner}/>{days.map((d,i)=><button className={`${s.dayHead} ${selected===i?s.selected:""}`} onClick={()=>setSelected(i)} key={d[1]}><span>{d[0]}</span><b>{d[1]}</b></button>)}<div className={s.times}>{hours.map(x=><span key={x}>{x}</span>)}</div><div className={s.grid}>{days.map((d,di)=><div className={`${s.col} ${selected===di?s.selectedCol:""}`} key={d[1]}>{shown.filter(e=>e[0]===di).map((e,i)=><Link href="/app/schedule" className={s.event} data-cat={e[5]} style={{top:e[1]*49,height:Math.max(47,e[2]*49)}} key={i}><b><I name={e[6]}/>{e[3]}</b><small>{e[4]}</small></Link>)}</div>)}</div></section>:<section className={s.list}><header><h2>{view==="month"?"September at a glance":"Your agenda"}</h2><span>{shown.length} planned activities</span></header>{shown.map((e,i)=><Link href="/app/schedule" key={i}><i data-cat={e[5]}><I name={e[6]}/></i><span><b>{e[3]}</b><small>{days[e[0]][0]}, {days[e[0]][1]} Sep · {e[4]}</small></span><I name="ChevronRight"/></Link>)}</section>}</>}
  {(module==="bookings"||module==="reminders"||module==="focus")&&<section className={s.modulePanel}><header><div><span><I name={module==="bookings"?"BookOpenCheck":module==="reminders"?"Bell":"Clock3"}/></span><div><h2>{moduleContent[module].title}</h2><p>{moduleContent[module].subtitle}</p></div></div><button><I name="Plus"/> {module==="bookings"?"New booking":module==="reminders"?"Add reminder":"New focus block"}</button></header><div className={s.moduleCards}>{moduleContent[module].items.map((item)=><article data-cat={item[3]} key={item[0]}><i><I name={item[2]}/></i><div><h3>{item[0]}</h3><p>{item[1]}</p><span>{module==="bookings"?"Confirmed":module==="reminders"?"Active":"Ready"}</span></div><button>{item[4]} <I name="ArrowRight"/></button></article>)}</div></section>}
 </main></HomeShell>
}
